from app.models.ai import AIConsentPolicy, AIModelConfiguration, AIUsageRecord
from app.models.auth import AuthSession, User
from app.models.file_ingestion import (
    EmbeddingJob,
    ExtractionResult,
    FileChunk,
    ProcessingFailure,
    ProcessingJob,
)
from app.models.file_vault import (
    Collection,
    CollectionItem,
    FileFavorite,
    FileRecord,
    FileTag,
    FileVersion,
    Tag,
    UploadRecord,
)
from app.models.foundation import (
    AuditLog,
    DomainEvent,
    Notification,
    UserPreferences,
    WorldProfile,
)
from app.models.habits import (
    DailyCheckIn,
    Habit,
    HabitLog,
    HabitSchedule,
    HabitStreak,
    HabitTarget,
    WeeklyReview,
)
from app.models.learning import (
    Attempt,
    Course,
    CourseModule,
    Flashcard,
    FlashcardReview,
    LearningGoal,
    LearningResource,
    Lesson,
    MasteryRecord,
    Question,
    Quiz,
    StudyRoadmap,
    StudySession,
    Subject,
    Topic,
    TopicRelation,
)
from app.models.mentors import (
    Conversation,
    ConversationMemorySettings,
    Mentor,
    MentorPermission,
    Message,
    MessageSource,
)
from app.models.search import RecentSearch

__all__ = [
    "AuditLog",
    "AIConsentPolicy",
    "AIModelConfiguration",
    "AIUsageRecord",
    "Attempt",
    "AuthSession",
    "Collection",
    "CollectionItem",
    "Conversation",
    "ConversationMemorySettings",
    "Course",
    "CourseModule",
    "DomainEvent",
    "EmbeddingJob",
    "ExtractionResult",
    "FileFavorite",
    "FileChunk",
    "FileRecord",
    "FileTag",
    "FileVersion",
    "Flashcard",
    "FlashcardReview",
    "DailyCheckIn",
    "Habit",
    "HabitLog",
    "HabitSchedule",
    "HabitStreak",
    "HabitTarget",
    "LearningGoal",
    "LearningResource",
    "Lesson",
    "MasteryRecord",
    "Mentor",
    "MentorPermission",
    "Message",
    "MessageSource",
    "Notification",
    "ProcessingFailure",
    "ProcessingJob",
    "Question",
    "Quiz",
    "RecentSearch",
    "StudyRoadmap",
    "StudySession",
    "Subject",
    "Tag",
    "Topic",
    "TopicRelation",
    "UploadRecord",
    "User",
    "UserPreferences",
    "WeeklyReview",
    "WorldProfile",
]
