import type { WorldInteractionManifestEntry } from "../schemas/world-manifest-schema";

export const WORLD_INTERACTIONS_MANIFEST: WorldInteractionManifestEntry[] = [
  {
    accessibilityLabel: "Continue the most relevant current activity from Central Plaza",
    commandRoute: "/app",
    gamepadAction: "primary",
    id: "interaction-plaza-continue-terminal",
    keyboardAction: "KeyE",
    locationId: "central-plaza",
    position: [0, 1.25, -18],
    prompt: "Continue Activity",
    radius: 3.2,
    type: "continue_last_activity"
  },
  {
    accessibilityLabel: "Open the daily overview from Central Plaza",
    commandRoute: "/app/habits",
    gamepadAction: "primary",
    id: "interaction-plaza-daily-terminal",
    keyboardAction: "KeyE",
    locationId: "habit-garden",
    position: [15.6, 1.25, -9],
    prompt: "Open Daily Overview",
    radius: 3.2,
    type: "open_habit_dashboard"
  },
  {
    accessibilityLabel: "Read notifications from Central Plaza",
    commandRoute: "/app",
    gamepadAction: "primary",
    id: "interaction-plaza-notifications-terminal",
    keyboardAction: "KeyE",
    locationId: "central-plaza",
    position: [15.6, 1.25, 9],
    prompt: "Read Notifications",
    radius: 3.2,
    type: "read_notification"
  },
  {
    accessibilityLabel: "Open the World Mode map and travel contracts from Central Plaza",
    commandRoute: "/app/world",
    gamepadAction: "primary",
    id: "interaction-plaza-map-terminal",
    keyboardAction: "KeyE",
    locationId: "central-plaza",
    position: [0, 1.25, 18],
    prompt: "Open World Map",
    radius: 3.2,
    type: "open_application_panel"
  },
  {
    accessibilityLabel: "Open fast travel from Central Plaza",
    commandRoute: "/app/world",
    gamepadAction: "primary",
    id: "interaction-plaza-fast-travel-terminal",
    keyboardAction: "KeyE",
    locationId: "central-plaza",
    position: [-15.6, 1.25, 9],
    prompt: "Fast Travel",
    radius: 3.2,
    type: "fast_travel"
  },
  {
    accessibilityLabel: "Open AI mentors from Central Plaza",
    commandRoute: "/app/ai",
    gamepadAction: "primary",
    id: "interaction-plaza-mentor-terminal",
    keyboardAction: "KeyE",
    locationId: "ai-observatory",
    position: [-15.6, 1.25, -9],
    prompt: "Open Mentors",
    radius: 3.2,
    type: "start_ai_conversation"
  },
  {
    accessibilityLabel: "Open the Knowledge Library in Command Mode",
    commandRoute: "/app/library",
    gamepadAction: "primary",
    id: "interaction-library-terminal",
    keyboardAction: "KeyE",
    locationId: "knowledge-library",
    position: [184, 0.36, -246],
    prompt: "Open Library",
    radius: 12,
    type: "open_file_collection"
  },
  {
    accessibilityLabel: "Browse Knowledge Library collections in Command Mode",
    commandRoute: "/app/library",
    gamepadAction: "primary",
    id: "interaction-library-collections-terminal",
    keyboardAction: "KeyE",
    locationId: "knowledge-library",
    position: [171, 1.25, -260],
    prompt: "Browse Collections",
    radius: 10,
    type: "open_file_collection"
  },
  {
    accessibilityLabel: "Search Knowledge Library files in Command Mode",
    commandRoute: "/app/library",
    gamepadAction: "primary",
    id: "interaction-library-search-terminal",
    keyboardAction: "KeyE",
    locationId: "knowledge-library",
    position: [184, 1.25, -267],
    prompt: "Search Files",
    radius: 10,
    type: "open_application_panel"
  },
  {
    accessibilityLabel: "Ask an AI mentor about ready Knowledge Library files",
    commandRoute: "/app/ai",
    gamepadAction: "primary",
    id: "interaction-library-ai-terminal",
    keyboardAction: "KeyE",
    locationId: "knowledge-library",
    position: [197, 1.25, -260],
    prompt: "Ask About Files",
    radius: 10,
    type: "start_ai_conversation"
  },
  {
    accessibilityLabel: "Ask an AI mentor in Command Mode",
    commandRoute: "/app/ai",
    gamepadAction: "primary",
    id: "interaction-ai-terminal",
    keyboardAction: "KeyE",
    locationId: "ai-observatory",
    position: [-198, 0.36, -252],
    prompt: "Ask AI",
    radius: 12,
    type: "start_ai_conversation"
  },
  {
    accessibilityLabel: "Open AI Observatory mentor conversations in Command Mode",
    commandRoute: "/app/ai",
    gamepadAction: "primary",
    id: "interaction-observatory-mentor-chat",
    keyboardAction: "KeyE",
    locationId: "ai-observatory",
    position: [-210, 1.25, -262],
    prompt: "Open Mentor Chat",
    radius: 10,
    type: "start_ai_conversation"
  },
  {
    accessibilityLabel: "Open citation-backed document question answering from AI Observatory",
    commandRoute: "/app/ai",
    gamepadAction: "primary",
    id: "interaction-observatory-document-qa",
    keyboardAction: "KeyE",
    locationId: "ai-observatory",
    position: [-198, 1.25, -269],
    prompt: "Open Document Q&A",
    radius: 10,
    type: "start_ai_conversation"
  },
  {
    accessibilityLabel: "Review provider and model status from AI Observatory",
    commandRoute: "/app/settings",
    gamepadAction: "primary",
    id: "interaction-observatory-provider-status",
    keyboardAction: "KeyE",
    locationId: "ai-observatory",
    position: [-186, 1.25, -262],
    prompt: "Review AI Settings",
    radius: 10,
    type: "open_application_panel"
  },
  {
    accessibilityLabel: "Open Habit Garden in Command Mode",
    commandRoute: "/app/habits",
    gamepadAction: "primary",
    id: "interaction-habit-terminal",
    keyboardAction: "KeyE",
    locationId: "habit-garden",
    position: [238, 0.36, 196],
    prompt: "Open Habits",
    radius: 12,
    type: "open_habit_dashboard"
  },
  {
    accessibilityLabel: "Log today's habits from Habit Garden in Command Mode",
    commandRoute: "/app/habits",
    gamepadAction: "primary",
    id: "interaction-garden-log-terminal",
    keyboardAction: "KeyE",
    locationId: "habit-garden",
    position: [224, 1.25, 186],
    prompt: "Log Today",
    radius: 10,
    type: "open_habit_dashboard"
  },
  {
    accessibilityLabel: "Create a habit from Habit Garden in Command Mode",
    commandRoute: "/app/habits",
    gamepadAction: "primary",
    id: "interaction-garden-create-terminal",
    keyboardAction: "KeyE",
    locationId: "habit-garden",
    position: [238, 1.25, 178],
    prompt: "Create Habit",
    radius: 10,
    type: "open_habit_dashboard"
  },
  {
    accessibilityLabel: "Review habit milestones from Habit Garden",
    commandRoute: "/app/achievements",
    gamepadAction: "primary",
    id: "interaction-garden-milestones-terminal",
    keyboardAction: "KeyE",
    locationId: "habit-garden",
    position: [252, 1.25, 186],
    prompt: "Review Milestones",
    radius: 10,
    type: "open_achievement_display"
  },
  {
    accessibilityLabel: "Open analytics in Command Mode",
    commandRoute: "/app/analytics",
    gamepadAction: "primary",
    id: "interaction-analytics-terminal",
    keyboardAction: "KeyE",
    locationId: "progress-tower",
    position: [340, 0.36, -52],
    prompt: "Open Analytics",
    radius: 12,
    type: "open_analytics"
  },
  {
    accessibilityLabel: "Open the Project Dock in Command Mode",
    commandRoute: "/app/projects",
    gamepadAction: "primary",
    id: "interaction-project-terminal",
    keyboardAction: "KeyE",
    locationId: "project-dock",
    position: [-148, 0.36, 276],
    prompt: "Open Projects",
    radius: 12,
    type: "open_project"
  },
  {
    accessibilityLabel: "Open Achievement Hall in Command Mode",
    commandRoute: "/app/achievements",
    gamepadAction: "primary",
    id: "interaction-achievement-terminal",
    keyboardAction: "KeyE",
    locationId: "achievement-hall",
    position: [78, 0.36, 344],
    prompt: "Open Achievements",
    radius: 12,
    type: "open_achievement_display"
  }
];
