import type { WorldInteractionManifestEntry } from "../schemas/world-manifest-schema";

export const WORLD_INTERACTIONS_MANIFEST: WorldInteractionManifestEntry[] = [
  {
    accessibilityLabel: "Continue the most relevant current activity from Central Plaza",
    commandRoute: "/app",
    gamepadAction: "primary",
    id: "interaction-plaza-continue-terminal",
    keyboardAction: "KeyE",
    locationId: "central-plaza",
    position: [0, 1.25, -18],
    prompt: "Continue Activity",
    radius: 3.2,
    type: "continue_last_activity"
  },
  {
    accessibilityLabel: "Open the daily overview from Central Plaza",
    commandRoute: "/app/habits",
    gamepadAction: "primary",
    id: "interaction-plaza-daily-terminal",
    keyboardAction: "KeyE",
    locationId: "habit-garden",
    position: [15.6, 1.25, -9],
    prompt: "Open Daily Overview",
    radius: 3.2,
    type: "open_habit_dashboard"
  },
  {
    accessibilityLabel: "Read notifications from Central Plaza",
    commandRoute: "/app",
    gamepadAction: "primary",
    id: "interaction-plaza-notifications-terminal",
    keyboardAction: "KeyE",
    locationId: "central-plaza",
    position: [15.6, 1.25, 9],
    prompt: "Read Notifications",
    radius: 3.2,
    type: "read_notification"
  },
  {
    accessibilityLabel: "Open the World Mode map and travel contracts from Central Plaza",
    commandRoute: "/app/world",
    gamepadAction: "primary",
    id: "interaction-plaza-map-terminal",
    keyboardAction: "KeyE",
    locationId: "central-plaza",
    position: [0, 1.25, 18],
    prompt: "Open World Map",
    radius: 3.2,
    type: "open_application_panel"
  },
  {
    accessibilityLabel: "Open fast travel from Central Plaza",
    commandRoute: "/app/world",
    gamepadAction: "primary",
    id: "interaction-plaza-fast-travel-terminal",
    keyboardAction: "KeyE",
    locationId: "central-plaza",
    position: [-15.6, 1.25, 9],
    prompt: "Fast Travel",
    radius: 3.2,
    type: "fast_travel"
  },
  {
    accessibilityLabel: "Open AI mentors from Central Plaza",
    commandRoute: "/app/ai",
    gamepadAction: "primary",
    id: "interaction-plaza-mentor-terminal",
    keyboardAction: "KeyE",
    locationId: "ai-observatory",
    position: [-15.6, 1.25, -9],
    prompt: "Open Mentors",
    radius: 3.2,
    type: "start_ai_conversation"
  },
  {
    accessibilityLabel: "Open the Knowledge Library in Command Mode",
    commandRoute: "/app/library",
    gamepadAction: "primary",
    id: "interaction-library-terminal",
    keyboardAction: "KeyE",
    locationId: "knowledge-library",
    position: [184, 0.36, -246],
    prompt: "Open Library",
    radius: 12,
    type: "open_file_collection"
  },
  {
    accessibilityLabel: "Browse Knowledge Library collections in Command Mode",
    commandRoute: "/app/library",
    gamepadAction: "primary",
    id: "interaction-library-collections-terminal",
    keyboardAction: "KeyE",
    locationId: "knowledge-library",
    position: [171, 1.25, -260],
    prompt: "Browse Collections",
    radius: 10,
    type: "open_file_collection"
  },
  {
    accessibilityLabel: "Search Knowledge Library files in Command Mode",
    commandRoute: "/app/library",
    gamepadAction: "primary",
    id: "interaction-library-search-terminal",
    keyboardAction: "KeyE",
    locationId: "knowledge-library",
    position: [184, 1.25, -267],
    prompt: "Search Files",
    radius: 10,
    type: "open_application_panel"
  },
  {
    accessibilityLabel: "Ask an AI mentor about ready Knowledge Library files",
    commandRoute: "/app/ai",
    gamepadAction: "primary",
    id: "interaction-library-ai-terminal",
    keyboardAction: "KeyE",
    locationId: "knowledge-library",
    position: [197, 1.25, -260],
    prompt: "Ask About Files",
    radius: 10,
    type: "start_ai_conversation"
  },
  {
    accessibilityLabel: "Ask an AI mentor in Command Mode",
    commandRoute: "/app/ai",
    gamepadAction: "primary",
    id: "interaction-ai-terminal",
    keyboardAction: "KeyE",
    locationId: "ai-observatory",
    position: [-198, 0.36, -252],
    prompt: "Ask AI",
    radius: 12,
    type: "start_ai_conversation"
  },
  {
    accessibilityLabel: "Open AI Observatory mentor conversations in Command Mode",
    commandRoute: "/app/ai",
    gamepadAction: "primary",
    id: "interaction-observatory-mentor-chat",
    keyboardAction: "KeyE",
    locationId: "ai-observatory",
    position: [-210, 1.25, -262],
    prompt: "Open Mentor Chat",
    radius: 10,
    type: "start_ai_conversation"
  },
  {
    accessibilityLabel: "Open citation-backed document question answering from AI Observatory",
    commandRoute: "/app/ai",
    gamepadAction: "primary",
    id: "interaction-observatory-document-qa",
    keyboardAction: "KeyE",
    locationId: "ai-observatory",
    position: [-198, 1.25, -269],
    prompt: "Open Document Q&A",
    radius: 10,
    type: "start_ai_conversation"
  },
  {
    accessibilityLabel: "Review provider and model status from AI Observatory",
    commandRoute: "/app/settings",
    gamepadAction: "primary",
    id: "interaction-observatory-provider-status",
    keyboardAction: "KeyE",
    locationId: "ai-observatory",
    position: [-186, 1.25, -262],
    prompt: "Review AI Settings",
    radius: 10,
    type: "open_application_panel"
  },
  {
    accessibilityLabel: "Open Habit Garden in Command Mode",
    commandRoute: "/app/habits",
    gamepadAction: "primary",
    id: "interaction-habit-terminal",
    keyboardAction: "KeyE",
    locationId: "habit-garden",
    position: [238, 0.36, 196],
    prompt: "Open Habits",
    radius: 12,
    type: "open_habit_dashboard"
  },
  {
    accessibilityLabel: "Log today's habits from Habit Garden in Command Mode",
    commandRoute: "/app/habits",
    gamepadAction: "primary",
    id: "interaction-garden-log-terminal",
    keyboardAction: "KeyE",
    locationId: "habit-garden",
    position: [224, 1.25, 186],
    prompt: "Log Today",
    radius: 10,
    type: "open_habit_dashboard"
  },
  {
    accessibilityLabel: "Create a habit from Habit Garden in Command Mode",
    commandRoute: "/app/habits",
    gamepadAction: "primary",
    id: "interaction-garden-create-terminal",
    keyboardAction: "KeyE",
    locationId: "habit-garden",
    position: [238, 1.25, 178],
    prompt: "Create Habit",
    radius: 10,
    type: "open_habit_dashboard"
  },
  {
    accessibilityLabel: "Review habit milestones from Habit Garden",
    commandRoute: "/app/achievements",
    gamepadAction: "primary",
    id: "interaction-garden-milestones-terminal",
    keyboardAction: "KeyE",
    locationId: "habit-garden",
    position: [252, 1.25, 186],
    prompt: "Review Milestones",
    radius: 10,
    type: "open_achievement_display"
  },
  {
    accessibilityLabel: "Resume a lesson from Learning Academy in Command Mode",
    commandRoute: "/app/learning",
    gamepadAction: "primary",
    id: "interaction-academy-resume-lesson",
    keyboardAction: "KeyE",
    locationId: "learning-academy",
    position: [-60, 1.25, -306],
    prompt: "Resume Lesson",
    radius: 10,
    type: "start_lesson"
  },
  {
    accessibilityLabel: "Open Learning Academy quizzes and practice in Command Mode",
    commandRoute: "/app/learning",
    gamepadAction: "primary",
    id: "interaction-academy-quiz-terminal",
    keyboardAction: "KeyE",
    locationId: "learning-academy",
    position: [-74, 1.25, -316],
    prompt: "Take Quiz",
    radius: 10,
    type: "start_lesson"
  },
  {
    accessibilityLabel: "Review flashcards from Learning Academy in Command Mode",
    commandRoute: "/app/learning",
    gamepadAction: "primary",
    id: "interaction-academy-flashcards-terminal",
    keyboardAction: "KeyE",
    locationId: "learning-academy",
    position: [-46, 1.25, -316],
    prompt: "Review Flashcards",
    radius: 10,
    type: "start_lesson"
  },
  {
    accessibilityLabel: "Ask an AI mentor from Learning Academy",
    commandRoute: "/app/ai",
    gamepadAction: "primary",
    id: "interaction-academy-mentor-terminal",
    keyboardAction: "KeyE",
    locationId: "learning-academy",
    position: [-60, 1.25, -324],
    prompt: "Ask Mentor",
    radius: 10,
    type: "start_ai_conversation"
  },
  {
    accessibilityLabel: "Open Learning Academy roadmaps in Command Mode",
    commandRoute: "/app/learning",
    gamepadAction: "primary",
    id: "interaction-academy-roadmap-terminal",
    keyboardAction: "KeyE",
    locationId: "learning-academy",
    position: [-60, 1.25, -340],
    prompt: "Open Roadmap",
    radius: 10,
    type: "open_application_panel"
  },
  {
    accessibilityLabel: "Open the saved-code workspace from Coding Arena",
    commandRoute: "/app/coding",
    gamepadAction: "primary",
    id: "interaction-arena-workspace-terminal",
    keyboardAction: "KeyE",
    locationId: "coding-arena",
    position: [-306, 1.25, 67],
    prompt: "Open Workspace",
    radius: 10,
    type: "open_application_panel"
  },
  {
    accessibilityLabel: "Choose a coding exercise from Coding Arena",
    commandRoute: "/app/coding",
    gamepadAction: "primary",
    id: "interaction-arena-exercise-terminal",
    keyboardAction: "KeyE",
    locationId: "coding-arena",
    position: [-313, 1.25, 93],
    prompt: "Choose Exercise",
    radius: 10,
    type: "open_application_panel"
  },
  {
    accessibilityLabel: "Open AI code explanation and review from Coding Arena",
    commandRoute: "/app/coding",
    gamepadAction: "primary",
    id: "interaction-arena-review-terminal",
    keyboardAction: "KeyE",
    locationId: "coding-arena",
    position: [-335, 1.25, 93],
    prompt: "Review Code",
    radius: 10,
    type: "open_application_panel"
  },
  {
    accessibilityLabel: "Inspect the isolated code-runner security boundary from Coding Arena",
    commandRoute: "/app/coding",
    gamepadAction: "primary",
    id: "interaction-arena-runner-terminal",
    keyboardAction: "KeyE",
    locationId: "coding-arena",
    position: [-342, 1.25, 76],
    prompt: "Runner Status",
    radius: 10,
    type: "open_application_panel"
  },
  {
    accessibilityLabel: "Open projects linked to Coding Arena workspaces",
    commandRoute: "/app/projects",
    gamepadAction: "primary",
    id: "interaction-arena-project-terminal",
    keyboardAction: "KeyE",
    locationId: "coding-arena",
    position: [-324, 1.25, 103],
    prompt: "Linked Projects",
    radius: 10,
    type: "open_project"
  },
  {
    accessibilityLabel: "Open analytics in Command Mode",
    commandRoute: "/app/analytics",
    gamepadAction: "primary",
    id: "interaction-analytics-terminal",
    keyboardAction: "KeyE",
    locationId: "progress-tower",
    position: [340, 0.36, -52],
    prompt: "Open Analytics",
    radius: 12,
    type: "open_analytics"
  },
  {
    accessibilityLabel: "Review learning progress from Progress Tower in Command Mode",
    commandRoute: "/app/learning",
    gamepadAction: "primary",
    id: "interaction-progress-learning-terminal",
    keyboardAction: "KeyE",
    locationId: "progress-tower",
    position: [326, 1.25, -62],
    prompt: "Learning Progress",
    radius: 10,
    type: "open_analytics"
  },
  {
    accessibilityLabel: "Review habit progress from Progress Tower in Command Mode",
    commandRoute: "/app/habits",
    gamepadAction: "primary",
    id: "interaction-progress-habits-terminal",
    keyboardAction: "KeyE",
    locationId: "progress-tower",
    position: [340, 1.25, -70],
    prompt: "Habit Progress",
    radius: 10,
    type: "open_analytics"
  },
  {
    accessibilityLabel: "Review project progress from Progress Tower in Command Mode",
    commandRoute: "/app/projects",
    gamepadAction: "primary",
    id: "interaction-progress-projects-terminal",
    keyboardAction: "KeyE",
    locationId: "progress-tower",
    position: [354, 1.25, -62],
    prompt: "Project Progress",
    radius: 10,
    type: "open_analytics"
  },
  {
    accessibilityLabel: "Open the Project Dock in Command Mode",
    commandRoute: "/app/projects",
    gamepadAction: "primary",
    id: "interaction-project-terminal",
    keyboardAction: "KeyE",
    locationId: "project-dock",
    position: [-148, 0.36, 276],
    prompt: "Open Projects",
    radius: 12,
    type: "open_project"
  },
  {
    accessibilityLabel: "Open the featured project from Project Dock",
    commandRoute: "/app/projects",
    gamepadAction: "primary",
    id: "interaction-dock-featured-project",
    keyboardAction: "KeyE",
    locationId: "project-dock",
    position: [-148, 1.25, 258],
    prompt: "Open Featured Project",
    radius: 10,
    type: "open_project"
  },
  {
    accessibilityLabel: "Review project milestones and tasks from Project Dock",
    commandRoute: "/app/projects",
    gamepadAction: "primary",
    id: "interaction-dock-work-terminal",
    keyboardAction: "KeyE",
    locationId: "project-dock",
    position: [-164, 1.25, 268],
    prompt: "Review Work",
    radius: 10,
    type: "open_project"
  },
  {
    accessibilityLabel: "Review open project blockers from Project Dock",
    commandRoute: "/app/projects",
    gamepadAction: "primary",
    id: "interaction-dock-blocker-terminal",
    keyboardAction: "KeyE",
    locationId: "project-dock",
    position: [-132, 1.25, 268],
    prompt: "Review Blockers",
    radius: 10,
    type: "open_project"
  },
  {
    accessibilityLabel: "Open project-linked files and context from Project Dock",
    commandRoute: "/app/projects",
    gamepadAction: "primary",
    id: "interaction-dock-files-terminal",
    keyboardAction: "KeyE",
    locationId: "project-dock",
    position: [-160, 1.25, 289],
    prompt: "Project Context",
    radius: 10,
    type: "open_file_collection"
  },
  {
    accessibilityLabel: "Open AI Hall for approval-controlled project assistance",
    commandRoute: "/app/ai",
    gamepadAction: "primary",
    id: "interaction-dock-ai-terminal",
    keyboardAction: "KeyE",
    locationId: "project-dock",
    position: [-136, 1.25, 289],
    prompt: "Open AI Hall",
    radius: 10,
    type: "start_ai_conversation"
  },
  {
    accessibilityLabel: "Open Achievement Hall in Command Mode",
    commandRoute: "/app/achievements",
    gamepadAction: "primary",
    id: "interaction-achievement-terminal",
    keyboardAction: "KeyE",
    locationId: "achievement-hall",
    position: [78, 0.36, 344],
    prompt: "Open Achievements",
    radius: 12,
    type: "open_achievement_display"
  },
  {
    accessibilityLabel: "Browse earned achievement exhibits from Achievement Hall",
    commandRoute: "/app/achievements",
    gamepadAction: "primary",
    id: "interaction-hall-achievements-gallery",
    keyboardAction: "KeyE",
    locationId: "achievement-hall",
    position: [78, 1.25, 326],
    prompt: "Browse Achievements",
    radius: 10,
    type: "open_achievement_display"
  },
  {
    accessibilityLabel: "Review saved certificates from Achievement Hall",
    commandRoute: "/app/settings",
    gamepadAction: "primary",
    id: "interaction-hall-certificates-gallery",
    keyboardAction: "KeyE",
    locationId: "achievement-hall",
    position: [62, 1.25, 337],
    prompt: "View Certificates",
    radius: 10,
    type: "open_achievement_display"
  },
  {
    accessibilityLabel: "Review completed projects from Achievement Hall",
    commandRoute: "/app/projects",
    gamepadAction: "primary",
    id: "interaction-hall-project-gallery",
    keyboardAction: "KeyE",
    locationId: "achievement-hall",
    position: [94, 1.25, 337],
    prompt: "Completed Projects",
    radius: 10,
    type: "open_project"
  },
  {
    accessibilityLabel: "Review earned world unlock identifiers from Achievement Hall",
    commandRoute: "/app/achievements",
    gamepadAction: "primary",
    id: "interaction-hall-world-unlocks",
    keyboardAction: "KeyE",
    locationId: "achievement-hall",
    position: [78, 1.25, 357],
    prompt: "World Unlocks",
    radius: 10,
    type: "open_achievement_display"
  }
];
