import type { WorldLocationManifestEntry } from "../schemas/world-manifest-schema";

export const WORLD_LOCATIONS_MANIFEST: WorldLocationManifestEntry[] = [
  {
    accessibilityLabel: "Central Plaza hub",
    assetId: "building-central-plaza",
    audioZone: "audio-central-plaza",
    backendLocationId: "central_plaza",
    commandRoute: "/app",
    environmentZone: "central-valley",
    fastTravelPoint: [0, 0.2, 24],
    id: "central-plaza",
    interactionRadius: 18,
    lodProfile: "landmark",
    name: "Central Plaza",
    performanceBudgetKey: "landmark-balanced",
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    theme: "aetherium",
    worldRadius: 64
  },
  {
    accessibilityLabel: "Knowledge Library district",
    assetId: "building-knowledge-library",
    audioZone: "audio-library",
    backendLocationId: "library",
    commandRoute: "/app/library",
    environmentZone: "library-river",
    fastTravelPoint: [166, 4, -214],
    id: "knowledge-library",
    interactionRadius: 16,
    lodProfile: "hero-building",
    name: "Knowledge Library",
    performanceBudgetKey: "district-balanced",
    position: [184, 8, -246],
    rotation: [0, 1.25, 0],
    theme: "knowledge",
    worldRadius: 58
  },
  {
    accessibilityLabel: "AI Observatory district",
    assetId: "building-ai-observatory",
    audioZone: "audio-observatory",
    backendLocationId: "ai_hall",
    commandRoute: "/app/ai",
    environmentZone: "observatory-rise",
    fastTravelPoint: [-162, 12, -220],
    id: "ai-observatory",
    interactionRadius: 16,
    lodProfile: "hero-building",
    name: "AI Observatory",
    performanceBudgetKey: "district-balanced",
    position: [-198, 28, -252],
    rotation: [0, -0.92, 0],
    theme: "research",
    worldRadius: 56
  },
  {
    accessibilityLabel: "Habit Garden district",
    assetId: "building-habit-garden",
    audioZone: "audio-garden",
    backendLocationId: "habit_garden",
    commandRoute: "/app/habits",
    environmentZone: "garden-grove",
    fastTravelPoint: [208, 3, 164],
    id: "habit-garden",
    interactionRadius: 18,
    lodProfile: "hero-building",
    name: "Habit Garden",
    performanceBudgetKey: "vegetation-low",
    position: [238, 2, 196],
    rotation: [0, -0.42, 0],
    theme: "growth",
    worldRadius: 72
  },
  {
    accessibilityLabel: "Learning Academy district",
    assetId: "building-learning-academy",
    audioZone: "audio-academy",
    backendLocationId: "research_laboratory",
    commandRoute: "/app/learning",
    environmentZone: "academy-terrace",
    fastTravelPoint: [-42, 18, -300],
    id: "learning-academy",
    interactionRadius: 17,
    lodProfile: "hero-building",
    name: "Learning Academy",
    performanceBudgetKey: "district-balanced",
    position: [-60, 24, -334],
    rotation: [0, 0.28, 0],
    theme: "learning",
    worldRadius: 68
  },
  {
    accessibilityLabel: "Coding Arena district",
    assetId: "building-coding-arena",
    audioZone: "audio-arena",
    backendLocationId: "programming_tower",
    commandRoute: "/app/coding",
    environmentZone: "arena-basin",
    fastTravelPoint: [-292, 4, 48],
    id: "coding-arena",
    interactionRadius: 17,
    lodProfile: "hero-building",
    name: "Coding Arena",
    performanceBudgetKey: "district-balanced",
    position: [-324, 4, 76],
    rotation: [0, 1.58, 0],
    theme: "coding",
    worldRadius: 62
  },
  {
    accessibilityLabel: "Project Dock district",
    assetId: "building-project-dock",
    audioZone: "audio-dock",
    backendLocationId: "project_workshop",
    commandRoute: "/app/projects",
    environmentZone: "project-waterfront",
    fastTravelPoint: [-114, 2, 238],
    id: "project-dock",
    interactionRadius: 17,
    lodProfile: "hero-building",
    name: "Project Dock",
    performanceBudgetKey: "district-balanced",
    position: [-148, 2, 276],
    rotation: [0, -1.1, 0],
    theme: "project",
    worldRadius: 66
  },
  {
    accessibilityLabel: "Progress Tower district",
    assetId: "building-progress-tower",
    audioZone: "audio-progress",
    backendLocationId: "command_center",
    commandRoute: "/app/analytics",
    environmentZone: "progress-ridge",
    fastTravelPoint: [306, 28, -28],
    id: "progress-tower",
    interactionRadius: 15,
    lodProfile: "landmark",
    name: "Progress Tower",
    performanceBudgetKey: "landmark-balanced",
    position: [340, 38, -52],
    rotation: [0, -1.46, 0],
    theme: "productivity",
    worldRadius: 54
  },
  {
    accessibilityLabel: "Achievement Hall district",
    assetId: "building-achievement-hall",
    audioZone: "audio-achievements",
    backendLocationId: "achievement_hall",
    commandRoute: "/app/achievements",
    environmentZone: "achievement-approach",
    fastTravelPoint: [58, 10, 310],
    id: "achievement-hall",
    interactionRadius: 16,
    lodProfile: "hero-building",
    name: "Achievement Hall",
    performanceBudgetKey: "district-balanced",
    position: [78, 14, 344],
    rotation: [0, 3.05, 0],
    theme: "achievement",
    worldRadius: 60
  },
  {
    accessibilityLabel: "Personal Sanctuary district",
    assetId: "building-personal-sanctuary",
    audioZone: "audio-sanctuary",
    backendLocationId: "personal_home",
    commandRoute: "/app/settings",
    environmentZone: "sanctuary-overlook",
    fastTravelPoint: [300, 38, 278],
    id: "personal-sanctuary",
    interactionRadius: 15,
    lodProfile: "hero-building",
    name: "Personal Sanctuary",
    performanceBudgetKey: "district-low",
    position: [334, 44, 312],
    rotation: [0, -2.4, 0],
    theme: "personal",
    worldRadius: 52
  }
];
